# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\"N\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\naccumulate\x18\x02 \x01(\x08\x12\x1b\n\x13is_natural_language\x18\x03 \x01(\x08\"\x9c\x01\n\rQueryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1d\n\x15number_of_all_samples\x18\x03 \x01(\x05\x12%\n\x1dnumber_of_samples_in_the_loop\x18\x04 \x01(\x05\x12#\n\x1bnumber_of_discarded_samples\x18\x05 \x01(\x05\"\x91\x01\n\x0eSamplesRequest\x12\x13\n\x0bstart_index\x18\x01 \x01(\x05\x12\x13\n\x0brecords_cnt\x18\x02 \x01(\x05\x12 \n\x18include_transformed_data\x18\x03 \x01(\x08\x12\x18\n\x10include_raw_data\x18\x04 \x01(\x08\x12\x19\n\x11stats_to_retrieve\x18\x05 \x03(\t\"Z\n\x08\x44\x61taStat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05value\x18\x04 \x03(\x02\x12\x14\n\x0cvalue_string\x18\x05 \x01(\t\">\n\nDataRecord\x12\x11\n\tsample_id\x18\x01 \x01(\x05\x12\x1d\n\ndata_stats\x18\x02 \x03(\x0b\x32\t.DataStat\"V\n\x0fSamplesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x0c\x64\x61ta_records\x18\x03 \x03(\x0b\x32\x0b.DataRecord2k\n\x0b\x44\x61taService\x12+\n\nApplyQuery\x12\r.QueryRequest\x1a\x0e.QueryResponse\x12/\n\nGetSamples\x12\x0f.SamplesRequest\x1a\x10.SamplesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=22
  _globals['_QUERYREQUEST']._serialized_end=100
  _globals['_QUERYRESPONSE']._serialized_start=103
  _globals['_QUERYRESPONSE']._serialized_end=259
  _globals['_SAMPLESREQUEST']._serialized_start=262
  _globals['_SAMPLESREQUEST']._serialized_end=407
  _globals['_DATASTAT']._serialized_start=409
  _globals['_DATASTAT']._serialized_end=499
  _globals['_DATARECORD']._serialized_start=501
  _globals['_DATARECORD']._serialized_end=563
  _globals['_SAMPLESRESPONSE']._serialized_start=565
  _globals['_SAMPLESRESPONSE']._serialized_end=651
  _globals['_DATASERVICE']._serialized_start=653
  _globals['_DATASERVICE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
