// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "data_service.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DataService } from "./data_service";
import type { SamplesResponse } from "./data_service";
import type { SamplesRequest } from "./data_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { QueryResponse } from "./data_service";
import type { QueryRequest } from "./data_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * DataService: a unified interface for all data operations
 *
 * @generated from protobuf service DataService
 */
export interface IDataServiceClient {
    /**
     * @generated from protobuf rpc: ApplyQuery
     */
    applyQuery(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse>;
    /**
     * @generated from protobuf rpc: GetSamples
     */
    getSamples(input: SamplesRequest, options?: RpcOptions): UnaryCall<SamplesRequest, SamplesResponse>;
}
/**
 * DataService: a unified interface for all data operations
 *
 * @generated from protobuf service DataService
 */
export class DataServiceClient implements IDataServiceClient, ServiceInfo {
    typeName = DataService.typeName;
    methods = DataService.methods;
    options = DataService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ApplyQuery
     */
    applyQuery(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryRequest, QueryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSamples
     */
    getSamples(input: SamplesRequest, options?: RpcOptions): UnaryCall<SamplesRequest, SamplesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SamplesRequest, SamplesResponse>("unary", this._transport, method, opt, input);
    }
}
